In [1]:
# numpy : 배열등을 처리하기 쉽게 제공하는 모듈
import numpy as np

In [4]:
arr = np.arange(15)   #
print(type(arr),arr)


<class 'numpy.ndarray'> [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [ ]:
list_a = list(range(15))  # np.arange(start,stop,step)
print(type(list_a),list_a)

In [18]:
# 차원 변경 : array.reshape(행, 열)
arr = np.arange(15) 
arr = arr.reshape(3,5) 
print(arr.ndim)# 차원
print(arr.shape) # 배열의 형태
print(arr.size) # 배열의 전체 데이터 갯수
print(arr.dtype.name, arr.dtype.itemsize) # 데이터 타입의 이름, 저장 사이즈
print(arr)

arr.reshape(arr.size)    # 리스트 평탄화

2
(3, 5)
15
int32 4
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
import pandas as pd
df = pd.DataFrame(arr,columns = ["영","영","영","영","영"], index = ["하나","둘","셋"])
df

영   영   영   영   영
하나   0   1   2   3   4
둘    5   6   7   8   9
셋   10  11  12  13  14

In [107]:
# 리스트를 array로 변경
arr_list = np.array(list_a)
print(arr_list)


two_list = np.array([[1,2,3],[4,5,6]])
two_list

# # 각 array의 차원, 배열 형식 , 전체 사이즈, 데이터타입 출력
# print(arr_list.ndim, arr_list.shape,arr_list.size,arr_list.dtype)
# print(two_list.ndim, two_list.shape,two_list.size,two_list.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
# array 생성

a = np.empty((3,4))  # 메모리에 공간만! 할당 (값은 초기화 시키지 않아요!)
print(a)
a

# 초기값을 0으로 부여하면서 배열을 생성
a = np.zeros((2,3))
print(a)
print()
a = np.zeros((2,3),dtype = "i") # 데이터 타입을 int로
print(a)
print()

a = np.zeros((2,3),dtype = "U4") # 데이터 타입을 문자로
print(a)
print()

a = np.zeros((2,3),dtype = "f") # 데이터 타입을 float로
print(a)
print()

a = np.zeros((2,3),dtype = "i8") # 데이터 타입을 문자로
print(a, a.dtype.itemsize)
print()

#데이터 초기값을 1로 주면서 배열 생성
a = np.ones((2,3))
print(a)

b = np.zeros_like(a)
b

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]

[[0 0 0]
 [0 0 0]]

[['' '' '']
 ['' '' '']]

[[0. 0. 0.]
 [0. 0. 0.]]

[[0 0 0]
 [0 0 0]] 8

[[1. 1. 1.]
 [1. 1. 1.]]


array([[0., 0., 0.],
       [0., 0., 0.]])

In [42]:
# array 연산

x1 = np.array([1.0, 2.0, 3.0])
y1 = np.array([5.0, 10.0, 15.0])
x2 = np.array([[1.0, 2.0],[ 3.0, 4.0]]) 
y2 = np.array([[5.0,10.0],[15.0,20.0]]) 
z1 = np.array([-1.0, -2.0])
z2 = np.array([[5.0],[10.0],[15.0]])



In [54]:
# array basic 연산
print(x1 + y1)
print()

print(x2 * y2)
print()

print(y2 / z1)
print()

# array broadcast 연산
print(z1 + z2)   # 차원이 다를때 행렬 연산 진행한다 ()
print()
print(x1**2)
print(x1 >= 2)
print()
# shape
# x2 = np.array([[1.0, 2.0],[ 3.0, 4.0]]
x2.reshape(x2.size)
print(x2.flatten()) # 1 차원으로 평탄화

x2.flatten().reshape(2,2) # 다시 (2,2) 행렬로 만들어줌 # reshape 평탄화가 아니다!

[ 6. 12. 18.]

[[ 5. 20.]
 [45. 80.]]

[[ -5.  -5.]
 [-15. -10.]]

[[ 4.  3.]
 [ 9.  8.]
 [14. 13.]]

[1. 4. 9.]
[False  True  True]

[1. 2. 3. 4.]


array([[1., 2.],
       [3., 4.]])

In [63]:
# indexing, slicing, iterating
a = np.arange(10) ** 2
print(a)
print()

# 2번째 자료를 출력
print(a[2])

# 4부터16 까지 출력
print(a[2:5]) # [start:stop] stop은 포함하지 않음
print()
#처음부터 끝까지 2칸씩 증가시키면서 출력
print(a[::2])

a[0:6:2] = -a[0:6:2] #일대일 대응해서 -값을넣어준다.
print(a)
print()
# 뒤에서 부터 출력
print(a[::-1])

# for 문을 활용하여 출력 ( 그럼 역방향은?)
for i in a:
    print(i,end = " ")

[ 0  1  4  9 16 25 36 49 64 81]

4
[ 4  9 16]

[ 0  4 16 36 64]
[  0   1  -4   9 -16  25  36  49  64  81]

[ 81  64  49  36  25 -16   9  -4   1   0]
0 1 -4 9 -16 25 36 49 64 81 

In [82]:
# qodufdmf rjator
a = np.arange(1,20+1,1).reshape(4,5)
print(a)


# 배열의 각 원소검색 : array[행,열]
print(a[1,1])
print(a[0:2,1]) # 0행, 1행의 1열만

#마지막 행과 마지막 열의 자료 출력
# 1행의 모든 열 검색
print(a[-1,-1])
print(a[1,])
print(a[ : ,1])
print(a[[0,1],[0,3]])   # a[[행데이터],[열데이터]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
7
[2 7]
20
[ 6  7  8  9 10]
[ 2  7 12 17]
[1 9]


In [90]:
a = [[1,2,3],[4,5,6],[7,8,9]]
df = pd.DataFrame(a)
print(df)
df.iloc[[1,2],[0,1]]

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9


0  1
1  4  5
2  7  8

In [97]:
# np.ndarray(shape, buffer=)
a = np.ndarray((3,2), buffer = np.arange(6) dtype=int) ## dtype = int로 안주면 
# 8byte로 가져와서 숫자 두개씩 물림
# ndarray 로 빈껍데기 만들수 있는데 값이 할당되어 있다.

array([[ 4.,  3.],
       [ 9.,  8.],
       [14., 13.]])

In [98]:

# 실험용으로 이해하기 위해 자료를 가져옴
exam_data = {'수학' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100], '체육' : [ 100, 90, 90]}

df = pd.DataFrame(exam_data,index = ["서준","우현","인아"])
df


수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [102]:
df.drop(["서준","우현"], axis=0,inplace = True)
df.drop(["수학"], a/;xis=1, inplace = True)
df

영어   음악  체육
인아  95  100  90

In [106]:
x = np.array([18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
              2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

print(len(x))
print(x.min(),x.max(),x.std(),x.var()) # 표준편차
print(np.median(x),np.percentile(x,25))  # 왜 x.median이 아닐까?

26
-24 23 10.734628476137871 115.23224852071006
5.0 0.0


In [147]:
# 난수 생성 
#read : 0 부터 1 서이의 균일분포(정규분포)로 난수 생성
print(np.random.rand(10))
print(np.random.randn(10))
print(np.random.randint(10,size=10))
print(np.random.randint(10,20,size=10))

[0.7819296  0.31346703 0.09066788 0.93488741 0.01746235 0.69934213
 0.90405772 0.50427901 0.89963463 0.1048777 ]
[-0.70012369  0.85055862 -0.61816581 -0.70971331 -0.35736856  0.34383864
 -0.74669142  1.74313461 -0.59187886  0.66461236]
[0 5 9 5 6 5 3 9 2 8]
[13 11 17 11 13 18 17 18 14 10]


In [ ]:
# 난수 생성
rand : 0 부터 1사이의 균일분포(정규분포)로 난수생성
randn : 기댓값이 0이고 표

In [149]:
# 실습문제 
# 다음 행렬과 같은 배열이 있다.1
# x = np.array(arange(1:20))
# 이 배열에서 3의 배수를 찾아라
# 이 배열에서 4로 나누면 1이 남는 수를 찾아라
# 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.

x = np.arange(1,20+1)
x[x%3 == 0]   # 불립마스크
x[x%4 == 1]
print(x[(x%3 == 0) & (x%4 ==1)])

[9]
