# 시리즈 생성

In [2]:
# 판다스의 자료구조 : 시리즈, 데이터 프레임
import pandas as pd
sr = pd.Series({"a" : 1, "b" : 1, "c" : 1})
print(sr)


a    1
b    1
c    1
dtype: int64


In [59]:

# 시리즈 인덱스 값

print(sr.index)
print(sr.values)

Index(['a', 'b', 'c'], dtype='object')
[1 1 1]


In [65]:
# 시리즈를 접근하는 방법 : sr[index], sr[숫자인덱스]

print(sr["a"],sr[0])

print("\n")
print(sr["a":"c"])  ## 인덱스명으로 접근시 end 도 포함
print()
print(sr[0:2]) ## 숫자 인덱스명으로 접근시 end 불포함

1 1


a    1
b    1
c    1
dtype: int64

a    1
b    1
dtype: int64


In [68]:
# 리스트 또는 튜플을 시리즈로 만들면서 인덱스명 부여
list_data = ["영인", "220630","남",True]
sr1 = pd.Series(list_data, index = ["이름","생년월일","성별","학생여부"])
sr1

이름          영인
생년월일    220630
성별           남
학생여부      True
dtype: object

In [69]:
sr1[["이름","학생여부"]] ## 인덱스가 하나가 아니면 [[a,b]] 이런식으로

이름        영인
학생여부    True
dtype: object

In [72]:
sr1.dtype
sr.dtype # 시리즈에 저장된 데이터 타입 출력 판다스는 숫자->int64  문자 ->o

dtype('int64')

In [82]:
# 데이터 프레임 (시리즈가 여러개 묶인거) (키값이 columns)
# 딕셔너리로 데이터 프레임 생성 - > 키가 컬럼으로 된다.
dict_data = {"a":[1,2,3], "b":[4,5,6],"c":[7,8,9]}
df = pd.DataFrame(dict_data)
df

a  b  c
0  1  4  7
1  2  5  8
2  3  6  9

In [83]:
print(type(df))
df.dtypes # 각 컬럼의 데이터 타입
print(df.index) # 데이터프레임의 인덱스 출력
print(df.values)# 각 인덱스의 값 : 2차원 리스트

<class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=3, step=1)
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [89]:
# 2차원 리스트로 인덱스 명과 컬럼명을 부여하면서 데이터프레임 만들기
data = [[15,"남","덕명중"], [17,"여","수리중"]]

df = pd.DataFrame(data, index = ["준서","예은"], columns  = ["나이","성별",
                                                         "학교"])
df

나이 성별   학교
준서  15  남  덕명중
예은  17  여  수리중

In [95]:
print(df.dtypes)  #칼럼의 데이터 타입을 출력
print()
print(df.index) # 인덱스 번호 출력
print()
print(df.columns)   # column들 출력



나이     int64
성별    object
학교    object
dtype: object

Index(['학생1', '학생2'], dtype='object')

Index(['나이', '성별', '학교'], dtype='object')
     나이 성별   학교
학생1  15  남  덕명중
학생2  17  여  수리중

     나이 성별   학교
학생1  15  남  덕명중
학생2  17  여  수리중


In [99]:
# 인덱스명를 바꿔주고 싶을때 : 객체.index = [인덱스명,..]
# 컬럼명를 바꿔주고 싶을때 : 객체.columns = [인덱스명,..]

df.index = ["학생1","학생2"]
print(df)
print()
df.columns = ["연령","남녀","소속"]
print(df)

     나이 성별   학교
학생1  15  남  덕명중
학생2  17  여  수리중

     연령 남녀   소속
학생1  15  남  덕명중
학생2  17  여  수리중


In [104]:
# 인덱스명과 컬럼명을 일부만 수정하고자 할 경우 : 
# object.rename(index = {old:new,.....})
# object.rename(columns = {old:new,.....})
# 남녀를 성별로 학생1을 준서로 수정

df.rename(index = {"학생1": "준서"},columns = {"남녀":"성별"}, inplace = True)
df


연령 성별   소속
준서   15  남  덕명중
학생2  17  여  수리중

# 리스트를 원소로 갖는 리스트를 2차원 배열로 만들기

In [26]:
import pandas as pd

df = pd.DataFrame([[15, "남", "성곡중"],[16, "여", "수주중"]],\
                  index = ["이지훈","한승연"],columns = ["나이", "성별", "학교"])
print(df) 
print("\n")
print(df.index)
print(df.columns)

     나이 성별   학교
이지훈  15  남  성곡중
한승연  16  여  수주중


Index(['이지훈', '한승연'], dtype='object')
Index(['나이', '성별', '학교'], dtype='object')


In [35]:
# 두개의 리스트를 원소로 갖는 리스트를 데이터프레임화 했을 경우 
# 리스트가 열로 들어간다.
import pandas as pd

df = pd.DataFrame([[15, "남", "성곡중"],[16, "여", "수주중"]])
print(df) 
print("\n")

# 리스트를 시리즈로 변환했을때 열로 들어감
se = pd.Series([1,2,3])
print("se는")
print(se)

# 리스트가 행으로 들어감
fd = pd.Series([[1,2,3],[3,4,5]])
print("fd는",)
print(fd)

    0  1    2
0  15  남  성곡중
1  16  여  수주중


se는
0    1
1    2
2    3
dtype: int64
fd는
0    [1, 2, 3]
1    [3, 4, 5]
dtype: object


In [50]:
import pandas as pd

## dataprame을 썻을때 리스트는 열로 들어감
df = pd.DataFrame([[15, "남", "성곡중"],[16, "여", "수주중"]],\
                                 index = ["준서", "예은"], \
                 columns = ["나이", "성별", "학교"])

print("\n")

# 열 이름중 "나이"를 "연령"으로, "성별"을 "남녀"로, "학교"를 "소속"으로 바꾸기
df.rename(columns = {"나이" : "연령", "성별" : "남녀", "학교" : "소속"}, \
                                             inplace = True)

# df의 행 인덱스 중에서, "준서"를 "학생1"로 "예은"을 "학생2"로
df.rename(index = {"준서" : "학생1", "예은" : "학생2"},\
                                 inplace = True)

df

연령 남녀   소속
학생1  15  남  성곡중
학생2  16  여  수주중

In [ ]:
exam_data = {'수학' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100], '체육' : [ 100, 90, 90]}

In [2]:
# 서준, 우현, 인아로 인덱스 설정 하면서 데이터 프레임 생성 (exam_data를 가지고)

exam_data = {'수학' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100], '체육' : [ 100, 90, 90]}

df = pd.DataFrame(exam_data,index = ["서준","우현","인아"])
df


NameError: name 'pd' is not defined

In [ ]:
# 행의 자료를 삭제 :  객체.drop(행인덱스 또는 배열, axis = 0)
# 열의 자료를 삭제 :  객체.drop(행인덱스 또는 배열, axis = 1)
# 서준과 우현의 자료를 삭제

In [1]:
df.drop(["서준","우현"], axis=0)
df.drop(["수학"], axis=1)
df

NameError: name 'df' is not defined

In [116]:
# exam_data를 데이터 프레임으로 생성
# 인덱스명 추가 서준 준서 인아
# 컬럼명 추가 : 국어 영어 수학 음악
# 음악 컬럼명을 체육으로 수정해서 기존 자료에 반영
# 영어 컬럼 자료 삭제: 기존자료에 반영하지 않음 결과만 확인
# 서준자료 삭제 기존 자료에 반영하지 않음 결과만 확인
# 주의! 데이터프레임화했을때리스트가 행으로 들어온다 딕셔너리는 열로
exam_data = {'국어' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '수학' : [ 85, 95, 100], '음악' : [ 100, 90, 90]}
df = pd.DataFrame(exam_data,index=["서준","준서","인아"])
df.rename(columns = {"음악":"체육"},inplace = True)  
print(df.drop(["영어"],axis = 1))
print()
print(df.drop("서준",axis = 0))
# 질문 df.index = [] 와 df.rename(index = {x:y0}) 차이점





    국어   수학   체육
서준  90   85  100
준서  80   95   90
인아  70  100   90

    국어  영어   수학  체육
준서  80  89   95  90
인아  70  95  100  90


In [120]:
df_copy = df
df_copy.drop("인아",axis = 0,inplace =True)


In [122]:
df

국어  영어  수학   체육
서준  90  98  85  100
준서  80  89  95   90

In [129]:
exam_data = {'국어' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '수학' : [ 85, 95, 100], '음악' : [ 100, 90, 90]}
df = pd.DataFrame(exam_data,index=["서준","준서","인아"])
df.rename(columns = {"음악":"체육"},inplace = True)  
print(df.drop(["영어"],axis = 1))
print()
print(df.drop("서준",axis = 0))

    국어   수학   체육
서준  90   85  100
준서  80   95   90
인아  70  100   90

    국어  영어   수학  체육
준서  80  89   95  90
인아  70  95  100  90


In [125]:
df_copy_1 = df.copy()
df_copy_1

국어  영어   수학   체육
서준  90  98   85  100
준서  80  89   95   90
인아  70  95  100   90

In [134]:
exam_data = {'국어' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '수학' : [ 85, 95, 100], '음악' : [ 100, 90, 90]}
df = pd.DataFrame(exam_data,index=["서준","준서","인아"])
df.rename(columns = {"음악":"체육"},inplace = True)  

df_copy_1 = df.copy()
df_copy_1.drop("인아",axis = 0, inplace = True)
df
df_copy_1

국어  영어  수학   체육
서준  90  98  85  100
준서  80  89  95   90

In [136]:
exam_data = {'국어' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '수학' : [ 85, 95, 100], '음악' : [ 100, 90, 90]}
df = pd.DataFrame(exam_data,index = ["서준","우현","인아"])

In [ ]:
# 행을 선택 : object.loc[인덱스]

#             object.iloc[정수인덱스] <- 정수형 인덱스로 선택
df.loc["서준"]
print
df.iloc[0]
# 범위로 선택: 서준과 우현의 자료 검색
# 인덱스 명으로 검색 object.loc[start:end] -> end 포함
# 정수 인덱스로 검색 object.iloc[start:end] -> end 미포함
print(df.loc["서준":"우현"]) ## 서준 부터 우현까지
print(df.iloc[0:2])

In [142]:
  # end 미포함
# 서준과 인아의 정보만 가져오기

df.loc[["서준","인아"]] ## 여러개 가져올때는 [[]]
print()
df.iloc[[0,2]]

    국어  영어  수학   음악
서준  90  98  85  100
우현  80  89  95   90



국어  영어   수학   음악
서준  90  98   85  100
인아  70  95  100   90

In [148]:
# 열을 선택 : object[컬럼명] object.[컬럼명]
df.수학

df.rename(columns = {"음악":"체육"}, inplace = True)
print(df[ ["수학","체육"] ])

     수학   체육
서준   85  100
우현   95   90
인아  100   90


In [151]:
# 원소 선택은 object.loc[ 행인덱스, 컬럼인덱스 ]
#             object.iloc[  행의정수인덱스, 컬럼정수인덱스]
# 행을 슬라이싱 : object.loc [시작인덱스:끝 인덱스:간격(오프셋)]
print(df.iloc[0:3:2])
print(df.iloc[::2])
print(df.iloc[::-1])
# 인아의 수학과 체육의 점수를 출력하려고 한다.
df.loc["인아",["수학","체육"]]  ## 이름인덱스
df.iloc[-1, [0,-1]]   ## 위치 인덱스



    국어  영어   수학   체육
서준  90  98   85  100
인아  70  95  100   90
    국어  영어   수학   체육
서준  90  98   85  100
인아  70  95  100   90
    국어  영어   수학   체육
인아  70  95  100   90
우현  80  89   95   90
서준  90  98   85  100


국어    70
체육    90
Name: 인아, dtype: int64

In [180]:
# 서준부터 우현까지 수학에서 음악 점수를 출력

df.rename(columns = {"체육" : "음악"}, inplace = True)
df.loc["서준": "우현","수학" : "음악"]
df

국어   영어   수학   음악   음악
서준   77  100   77  100  100
우현   88   89   77   90  200
인아  100   95  100   90  300
자훈  100  100  100  100  100

In [184]:
# 열 추가 : object["새로운컬럼명"] = 값
# "국어" 점수 추가 100
# df.drop("자훈",axis = 0,inplace = True)
df

국어   영어   수학   음악   음악
서준   77  100   77  100  100
우현   88   89   77   90  200
인아  100   95  100   90  300

In [185]:
# 서준의 영어 점수를 100으로 수정
# df.loc["서준", "영어"] = 100
df.iloc[0,1] = 100
df

국어   영어   수학   음악   음악
서준   77  100   77  100  100
우현   88   89   77   90  200
인아  100   95  100   90  300

In [186]:
# 서준의 수학 점수와 국어 점수를 77로 수정
df.loc["서준",["수학","국어"]] = 77
df

국어   영어   수학   음악   음악
서준   77  100   77  100  100
우현   88   89   77   90  200
인아  100   95  100   90  300

In [188]:
# 우현의 수학 점수와 국어 점수를 77 88로 수정
df.loc["우현",["수학","국어"]] = 77,88
df

국어   영어   수학   음악   음악
서준   77  100   77  100  100
우현   88   89   77   90  200
인아  100   95  100   90  300

In [196]:
# 행과 열의 위치 변경 : object.tranpose(), object.T

df.T

서준  우현   인아
국어   77  88  100
영어  100  89   95
수학   77  77  100

In [ ]:
# 시리즈를 생성 : pandas.Series(딕셔너리 또는 리스트)
# 데이터 프레임생성 : pandas.DataFrame(데이타, index = ,columns = )
# 데이터 프레임의 인덱스 변경 : object.index = [인덱스명, ...]
# 컬럼명 변경 : object.columns = [컬럼명,.....]
# object 함수명( , ,..,inplace = True) 기존 자료를 변경
# 인덱스,컬럼 일부변경 : object.rename(index = {old:new},inplace = True)
#                       object.rename(columns = {old:new}, inplace = True)
# 인덱스와 컬럼삭제 : object.drop("인덱스명or컬럼명",inplace = True)
                                    # axis = 0 행 axis = 1 열
# 원소 수정 : object.loc[인덱스명, 컬럼명] = 값
# 행 추가 : object.loc[새로운 인덱스명]
# 열 추가 : object[새로운 열명] = 값
# 행의 자료 검색 : object.loc[행명], loc[start:end, 컬럼의 start:end]
# 열의 자료 검색 : object[열명]
# 인덱스와 컬럼의 위치 변경 : object.transpose(), object.T

In [ ]:
# 요소는 인덱스와 칼럼으로 들어감

In [197]:
exam_data = {"이름":["서준","우현","인아"],
            "수학" : [90,80,70],
            "영어" : [100,80,90],
            "음악" : [100,90,100],
            "체육" : [90,80,70]}
df = pd.DataFrame(exam_data)
df


이름  수학   영어   음악  체육
0  서준  90  100  100  90
1  우현  80   80   90  80
2  인아  70   90  100  70

In [203]:
# 특정칼럼을 인덱스로 설정 : object.set_index(칼럼명)
# print(df.set_index("이름",inplace = True))

df

수학   영어   음악  체육
이름                  
서준  90  100  100  90
우현  80   80   90  80
인아  70   90  100  70

In [205]:
# 인덱스 초기화 object.reset_index()
df.reset_index(inplace = True)
df

이름  수학   영어   음악  체육
0  서준  90  100  100  90
1  우현  80   80   90  80
2  인아  70   90  100  70

In [206]:
# ??

ndf = df.set_index("이름")
ndf


수학   영어   음악  체육
이름                  
서준  90  100  100  90
우현  80   80   90  80
인아  70   90  100  70

In [207]:
# 인덱스를 재배열 : object.reindex(인덱스리스트)
idx_list = ["서준","철수","우현","인아","나래"]
ndf_1 = ndf.reindex(idx_list)
ndf_1

수학     영어     음악    체육
이름                          
서준  90.0  100.0  100.0  90.0
철수   NaN    NaN    NaN   NaN
우현  80.0   80.0   90.0  80.0
인아  70.0   90.0  100.0  70.0
나래   NaN    NaN    NaN   NaN

In [211]:
# 인덱스 값으로 정렬 : object.sort_index()
ndf_1.sort_index()
ndf_1

수학     영어     음악    체육
이름                          
서준  90.0  100.0  100.0  90.0
철수   NaN    NaN    NaN   NaN
우현  80.0   80.0   90.0  80.0
인아  70.0   90.0  100.0  70.0
나래   NaN    NaN    NaN   NaN

In [213]:
# 컬럼을 기준으로 정렬: object.sort_values(by = 컬럼,ascending(오름차순) = False)
ndf.sort_values(by = ["수학"],ascending=False)
ndf.sort_values(by = ["음악","수학"],ascending=False)

수학   영어   음악  체육
이름                  
서준  90  100  100  90
인아  70   90  100  70
우현  80   80   90  80

In [ ]:
# df.set_index(), df.reset_index(),df.reindex(인덱스 리스트)
# df.sort_index(), df.sort_values(by = [컬럼, ,,,,], ascending = False)

# PART1 4. 산술연산

In [216]:
# 1. 시리즈 연산
# 시리즈 연산자 숫자
student1 = pd.Series({"국어":100,"영어":80,"수학" : 90})

#각 점수를 100으로 나눈 값을 출력
print(student1 / 100)
print(student1 + 100)

국어    1.0
영어    0.8
수학    0.9
dtype: float64
국어    200
영어    180
수학    190
dtype: int64


In [217]:
# 시리즈 vs 시리즈 연산 : 시리즈 연산자(+ - / *)
student2 = pd.Series({"국어":90,"영어":80,"수학" : 100})
student1 + student2

국어    190
영어    160
수학    190
dtype: int64

In [218]:
add = student1 + student2
sub = student1 - student2
mul = student1 * student2
div = student1 / student2
df = pd.DataFrame([add,sub,mul,div],
                 index = ["+","-","*","/"])
df

국어      영어      수학
+   190.000000   160.0   190.0
-    10.000000     0.0   -10.0
*  9000.000000  6400.0  9000.0
/     1.111111     1.0     0.9

In [221]:
# 연산식에 Nan 이 존재하면 연산의 결과는 Nan이다.
import numpy as np

stud1 = pd.Series({"국어": np.nan,"수학" : 100,"영어" : 80})
stud2 = pd.Series({"국어": 100,"수학" : 100})

add = stud1 + stud2
sub = stud1 - stud2
mul = stud1 * stud2 
div = stud1 / stud2

In [223]:
df= pd.DataFrame([add,sub,mul,div], index = ["+","-","*","/"])
df

국어       수학  영어
+ NaN    200.0 NaN
- NaN      0.0 NaN
* NaN  10000.0 NaN
/ NaN      1.0 NaN

In [224]:
# 데이타프레임 연산
# 데이타프레임 연산자(+ - * /) 숫자
# seaborn에서 제공하는 dataset을 로드
import seaborn as sns

# titanic 데이터 셋을 불러옴 : sns.loadset("titanic")
titanic = sns.load_dataset("titanic")
titanic


survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [235]:

# titanic 에서 age와 fare 의 컬럼의 정보만 가져와서 df에 저장
df = titanic[["age","fare"]] # 칼럼의 정보만 추출
# 100번재부터 200번재 까지의 "age"와 "fare"컬럼만 추출

df = titanic.loc[ : ,["age","fare"] ]
# df = titanic.loc[100 : 200,["age","fare"] ]
# df

#df.gead(): 처음부터 5개만 보여준다. df.gead(10) 10개보여줌 df.tail()뒤에서부터 5
df.head(10)
# df.tail()

age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500
5   NaN   8.4583
6  54.0  51.8625
7   2.0  21.0750
8  27.0  11.1333
9  14.0  30.0708

In [236]:
add_df = df + 10
add_df.tail()

age   fare
886  37.0  23.00
887  29.0  40.00
888   NaN  33.45
889  36.0  40.00
890  42.0  17.75

In [240]:
sr_age = titanic.loc[: ,"age"]
type(sr_age)
(sr_age+100).head()

0    122.0
1    138.0
2    126.0
3    135.0
4    135.0
Name: age, dtype: float64

In [259]:
# mpg 데이터셋을 로드해서
df_mpg = sns.load_dataset("mpg")
# df_mpg.info()
# 1. mpg, weight 컬럼을 추출해서 데이터 프레임으로 생성 한 후
df = pd.DataFrame(df_mpg[["mpg","weight"]])
# 2. 각 원소에 100을 더한 값을 출력
df + 100
# 3. 데이터프레임을 처음 10개의 정보만 출력
df.head(10)
# 4. 처음부터 100개의 행만 추출하여 mpg_sample 데이터프레임 생성
map_sample = df.iloc[ :100]
map_sample
# 5. 컬럼 (지훈) 추가하기
# map_sample["지훈"] = 100
# 6. 행에 (지훈) 추가하기    ===> 요거 틀림
map_sample.loc["지훈"] = 100
map_sample



C:\Users\HPE\AppData\Local\Temp\ipykernel_9928\510264537.py:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  map_sample.loc["지훈"] = 100


mpg  weight
0    18.0    3504
1    15.0    3693
2    18.0    3436
3    16.0    3433
4    17.0    3449
..    ...     ...
96   13.0    3821
97   18.0    3121
98   16.0    3278
99   18.0    2945
지훈  100.0     100

[101 rows x 2 columns]

mpg  weight
0   18.0    3504
1   15.0    3693
2   18.0    3436
3   16.0    3433
4   17.0    3449
..   ...     ...
95  12.0    4951
96  13.0    3821
97  18.0    3121
98  16.0    3278
99  18.0    2945

[100 rows x 2 columns]

In [6]:

Se = pd.DataFrame([[1,2,3],
                   [4,5,6]])
Se

0  1  2
0  1  2  3
1  4  5  6

In [3]:
df.shape

NameError: name 'df' is not defined